/* eslint-disable @typescript-eslint/ban-types */
import { ThemeFile } from './types';

const Themes: { [id: number]: ThemeFile } & Object = {
  1: {
    price: 70_000,
    type: 'table',
    theme: 'blue',
  },
  2: {
    price: 140_000,
    theme: 'upsidedown',
    type: 'profile',
    colorCompatible: true,
    imageCompatible: false,
    needApiData: true,
  },
  3: {
    price: 0,
    theme: 'default',
    type: 'profile',
    colorCompatible: true,
    imageCompatible: false,
    needApiData: true,
  },
  4: {
    price: 0,
    theme: 'default',
    type: 'cards',
  },
  5: {
    price: 0,
    theme: 'green',
    type: 'table',
  },
  6: {
    price: 0,
    theme: 'red',
    type: 'card_background',
  },
  7: {
    price: 420_666,
    theme: 'death',
    type: 'cards',
  },
  8: {
    price: 42_000,
    theme: 'blue',
    type: 'card_background',
  },
  9: {
    price: 49_000,
    theme: 'cute_menhera',
    type: 'card_background',
  },
  10: {
    price: 63_000,
    theme: 'premium',
    type: 'card_background',
  },
  11: {
    price: 70_000,
    theme: 'red',
    type: 'table',
  },
  12: {
    price: 84_000,
    theme: 'pink',
    type: 'table',
  },
  13: {
    price: 105_000,
    theme: 'rounded',
    type: 'table',
  },
  14: {
    price: 175_000,
    type: 'profile',
    theme: 'christmas_2021',
    colorCompatible: true,
    imageCompatible: true,
    customEdits: ['useImage'],
    needApiData: true,
  },
  15: {
    price: 168_000,
    type: 'profile',
    theme: 'warrior',
    colorCompatible: true,
    imageCompatible: true,
    customEdits: ['useImage'],
    needApiData: true,
  },
  16: {
    price: 168_000,
    type: 'profile',
    theme: 'fortification',
    colorCompatible: true,
    imageCompatible: true,
    customEdits: ['useImage'],
    needApiData: true,
  },
  17: {
    price: 133_000,
    type: 'profile',
    theme: 'kawaii',
    colorCompatible: true,
    imageCompatible: false,
    needApiData: true,
  },
  18: {
    price: 63_000,
    theme: 'kawaii',
    type: 'card_background',
  },
  19: {
    price: 119_000,
    type: 'table',
    theme: 'gauderios',
  },
  20: {
    price: 70_000,
    type: 'card_background',
    theme: 'lamenta_caelorum',
  },
  21: {
    price: 273_000,
    theme: 'without_soul',
    type: 'profile',
    colorCompatible: true,
    imageCompatible: false,
    needApiData: false,
  },
  22: {
    price: 245_000,
    theme: 'id03',
    type: 'profile',
    colorCompatible: true,
    imageCompatible: false,
    needApiData: true,
  },
  23: {
    price: 140_000,
    theme: 'atemporal',
    type: 'table',
  },
  24: {
    price: 175_000,
    type: 'profile',
    theme: 'gatito',
    colorCompatible: false,
    imageCompatible: false,
    needApiData: true,
  },
  25: {
    price: 0,
    type: 'eb_background',
    theme: 'default',
  },
  26: {
    price: 0,
    type: 'eb_text_box',
    theme: 'default',
  },
  27: {
    price: 0,
    type: 'eb_menhera',
    theme: 'default',
  },
  28: {
    price: 35_000,
    type: 'eb_text_box',
    theme: 'xp',
  },
  29: {
    price: 52_500,
    type: 'eb_background',
    theme: 'xp',
  },
  30: {
    price: 122_500,
    type: 'profile',
    theme: 'mural',
    colorCompatible: true,
    imageCompatible: true,
    customEdits: ['upperTextBoxFilled', 'bottomTextBoxFilled', 'whiteUpperText', 'whiteBottomText'],
    needApiData: true,
  },
  31: {
    price: 182_000,
    type: 'profile',
    theme: 'hello_kitty',
    colorCompatible: false,
    imageCompatible: false,
    needApiData: true,
  },
  32: {
    price: 385_001,
    type: 'cards',
    theme: 'hello_kitty',
  },
  33: {
    price: 147_000,
    type: 'table',
    theme: 'hello_kitty',
  },
  34: {
    price: 84_000,
    type: 'card_background',
    theme: 'hello_kitty',
  },
  35: {
    price: 56_000,
    type: 'eb_text_box',
    theme: 'hello_kitty',
  },
  36: {
    price: 210_000,
    type: 'eb_menhera',
    theme: 'hello_kitty',
  },
  37: {
    price: 59_500,
    type: 'eb_background',
    theme: 'hello_kitty',
  },
  38: {
    price: 59_500,
    type: 'card_background',
    theme: 'nocturnal',
  },
  39: {
    price: 73_500,
    type: 'profile',
    theme: 'sunflower',
    colorCompatible: true,
    imageCompatible: false,
    needApiData: false,
  },
  40: {
    price: 56_000,
    type: 'profile',
    theme: 'gallery',
    colorCompatible: true,
    imageCompatible: false,
    needApiData: false,
  },
  41: {
    price: 345_000,
    type: 'cards',
    theme: 'night',
  },
  42: {
    price: 45_000,
    type: 'card_background',
    theme: 'morning',
  },
  43: {
    price: 45_000,
    type: 'card_background',
    theme: 'frostbite',
  },
  44: {
    price: 55_000,
    type: 'profile',
    theme: 'website',
    colorCompatible: false,
    imageCompatible: false,
    needApiData: false,
  },
  45: {
    price: 100_000,
    type: 'profile',
    theme: 'memories',
    colorCompatible: true,
    imageCompatible: true,
    needApiData: true,
    customEdits: ['useImage', 'whiteUpperText', 'whiteBottomText'],
  },
  46: {
    price: 55_000,
    type: 'profile',
    theme: 'frozen',
    colorCompatible: false,
    imageCompatible: false,
    needApiData: false,
  },
  47: {
    price: 100_000,
    type: 'profile',
    theme: 'comuna_patrio',
    colorCompatible: true,
    imageCompatible: true,
    needApiData: true,
    customEdits: ['useImage', 'communistTheme', 'patriotTheme'],
  },
  48: {
    price: 50_000,
    type: 'card_background',
    theme: 'berserk',
  },
  49: {
    price: 23_500,
    type: 'card_background',
    theme: 'sunflower',
  },
  50: {
    price: 15_000,
    type: 'card_background',
    theme: 'hes_looking',
  },
};

export default Themes;
