name: Pull Request
description: Make a Pull Request
assignees:
  - ySnoopyDogy
body:
  - type: markdown
    attributes:
      value: |
        Thanks for creating a pull request. Please fill the form bellow to continue
  - type: textarea
    id: reason
    attributes:
      label: Reason
      description: Why should this change be made?
      placeholder: Today's code is kinda borring, with this, the code will be more awesome
    validations:
      required: true