files:
  - source: /src/locales/en-US
    translation: /src/locales/crowdin/%locale_with_underscore%/%original_file_name%

commit_message: ':globe_with_meridians: | Novas traduções para %original_file_name% (%language%)'
append_commit_message: false
