files:
  - source: /src/locales/en_US
    translation: /src/locales/%locale_with_underscore%/%original_file_name%

commit_message: '🌐 | Novas traduções para %original_file_name% (%language%)'
append_commit_message: false
