name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["\U0001F41B Bug", "❓ Help Wanted"]
assignees:
  - ySnoopyDogy
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of what the problem is.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide clear and concise steps for us to reliably reproduce this issue.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos
      description: Provide a screenshot and/or video demonstrating the issue being experienced.
    validations:
      required: false