import { createDesiredPropertiesObject } from '@discordeno/bot';

const desiredProperties = createDesiredPropertiesObject({
  user: {
    avatar: true,
    discriminator: true,
    globalName: true,
    id: true,
    locale: true,
    toggles: true,
    username: true,
    publicFlags: true,
  },
  attachment: {
    contentType: true,
    url: true,
    description: false,
    ephemeral: false,
    filename: false,
    id: true,
    flags: false,
    width: true,
    height: true,
    proxyUrl: true,
  },
  component: {
    component: true,
    channelTypes: true,
    components: true,
    content: true,
    customId: true,
    defaultValues: true,
    description: true,
    disabled: true,
    divider: true,
    accessory: true,
    accentColor: true,
    emoji: true,
    file: true,
    id: true,
    items: true,
    label: true,
    maxLength: true,
    maxValues: true,
    media: true,
    minLength: true,
    minValues: true,
    name: true,
    options: true,
    placeholder: true,
    required: true,
    size: true,
    spacing: true,
    spoiler: true,
    style: true,
    type: true,
    url: true,
    value: true,
    values: true,
  },
  messageInteractionMetadata: {
    id: true,
    interactedMessageId: true,
    originalResponseMessageId: true,
    targetMessageId: false,
    targetUser: false,
    triggeringInteractionMetadata: true,
    type: true,
    user: true,
  },
  guild: {
    id: true,
    members: true,
    preferredLocale: true,
  },
  channel: {
    id: true,
  },
  interaction: {
    applicationId: true,
    appPermissions: true,
    attachmentSizeLimit: false,
    channel: true,
    channelId: true,
    context: true,
    authorizingIntegrationOwners: false,
    data: true,
    guild: true,
    guildId: true,
    guildLocale: true,
    id: true,
    member: true,
    message: true,
    locale: true,
    token: true,
    type: true,
    user: true,
    version: false,
  },
  messageInteraction: { id: true, member: true, name: true, type: true, user: true },
  member: {
    avatar: true,
    guildId: true,
    id: true,
    nick: true,
    permissions: true,
    toggles: true,
    user: true,
  },
  message: {
    interaction: true,
    content: true,
    embeds: true,
    components: true,
    applicationId: true,
    attachments: true,
    interactionMetadata: true,
    id: true,
    guildId: true,
    channelId: true,
  },

});

export { desiredProperties };
