name: Build and publish Menhera images

on:
  workflow_run:
    workflows: [Test]
    types:
      - completed
    branches:
      - production

jobs:
  build-and-publish-images:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:

      - name: Check if all tests passed
        if: ${{ github.event.workflow_run.conclusion != 'success' }}
        run: |
          echo "::error title=Tests Failed::I refuse to publish a broken image! Fix Tests >.<"
          exit 1

      - uses: actions/checkout@v3

      - name: Build REST image
        run: docker build . --file Dockerfile --tag rest --target rest --label "runnumber=${GITHUB_RUN_ID}"

      - name: Build EVETS image
        run: docker build . --file Dockerfile --tag events --target events --label "runnumber=${GITHUB_RUN_ID}"

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Read REST package.json
        id: rest
        uses: jaywcjlove/github-action-read-file@main
        with:
          path: packages/rest/package.json

      - name: Read EVENTS package.json
        id: events
        uses: jaywcjlove/github-action-read-file@main
        with:
          path: packages/events/package.json

      - name: Prepare both image versions
        id: versions
        run: |
          echo "events::$(echo "${{steps.events.outputs.content}}" | grep 'version"' | cut -d '"' -f 4)" >> $GITHUB_OUTPUT
          echo "rest::$(echo "${{steps.rest.outputs.content}}"" | grep 'version"' | cut -d '"' -f 4)" >> $GITHUB_OUTPUT

      - name: Push both images
        run: |
          images=("rest" "events")
          for imgName in ${images[@]}
          do
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$imgName
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          CURRENT_VERSION=${{ steps.versions.outputs.rest }}

          if [ $imgName -eq 'events' ]; then
              CURRENT_VERSION=${{ steps.versions.outputs.events }}
          fi

          docker tag $imgName $IMAGE_ID:$CURRENT_VERSION
          docker push $IMAGE_ID:$CURRENT_VERSION
          done