name: Build and publish Menhera images

on:
  workflow_run:
    workflows: [Test]
    types:
      - completed
    branches:
      - production

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-publish-images:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:

      - name: Check if all tests passed
        if: ${{ github.event.workflow_run.conclusion != 'success' }}
        run: |
          echo "::error title=Tests Failed::I refuse to publish a broken image! Fix Tests >.<"
          exit 1

      - uses: actions/checkout@v3

      - name: Build rest image
        run: docker build . --file Dockerfile --tag rest --target rest --label "runnumber=${GITHUB_RUN_ID}"

      - name: Build events image
        run: docker build . --file Dockerfile --tag events --target events --label "runnumber=${GITHUB_RUN_ID}"

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Publish docker images
        run: |
          images=("rest" "events")
          for imgName in ${images[@]}
          do
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$imgName
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=latest
          docker tag $imgName $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
          done