name: Test

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      - uses: actions/setup-node@v3
        with:
          node-version: 18.4.0
          cache: 'yarn'
      
      - name: Install needed dependencies
        run: yarn install --frozen-lockfile

      - name: Run eslint 
        run: yarn run:lint

      - name: Execute typecheck in REST package
        run: yarn rest typecheck

      - name: Execute typecheck in EVENTS package
        run: yarn events typecheck

      - name: Execute typecheck in ORCHESTRATOR package
        run: yarn orchestrator typecheck

      - name: Execute jest in all packages
        run: yarn test
