name: Test

on:
  pull_request:
  push:

jobs:
  run-tests:
    runs-on: ${{matrix.os}}
    strategy:
      max-parallel: 24
      matrix:
        node-version: [18.4.x]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      
      - name: Install needed dependencies
        run: yarn install --frozen-lockfile

      - name: Run eslint 
        run: yarn run:lint

      - name: Execute typecheck in REST package
        run: yarn rest typecheck

      - name: Execute typecheck in EVENTS package
        run: yarn events typecheck

      - name: Execute jest in all packages
        run: yarn test
